name: Deploy

on: [push]
  # push:
  #   branches: [main]
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.4.1"
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.2"
      - run: swift run
        working-directory: ./deploy_new_version
        env:
          APPLE_APP_STORE_CONNECT_KEY: ${{ secrets.APPLE_APP_STORE_CONNECT_KEY }}
          APPLE_APP_STORE_CONNECT_KEY_ID: ${{ secrets.APPLE_APP_STORE_CONNECT_KEY_ID }}
          APPLE_APP_STORE_CONNECT_KEY_ISSUER_ID: ${{ secrets.APPLE_APP_STORE_CONNECT_KEY_ISSUER_ID }}
          XCODE_PROVISIONING_PROFILE: ${{ secrets.XCODE_PROVISIONING_PROFILE }}
          XCODE_SIGNING_CERT: ${{ secrets.XCODE_SIGNING_CERT }}
          XCODE_SIGNING_CERT_PASSWORD: ${{ secrets.XCODE_SIGNING_CERT_PASSWORD }}
